name: Build/release

on:
  push:
    ## Run on tags starting with `v*`
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    continue-on-error: true
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Install libarchive-tools for pacman build # Related https://github.com/electron-userland/electron-builder/issues/4181
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libarchive-tools

      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

       - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: this
          path: dist/
